name: matrix-analysis-2022
channels:
  - defaults
  - conda-forge
dependencies:
  - anyio=3.5.0
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - async_generator=1.10
  - attrs=21.4.0
  - babel=2.9.1
  - backcall=0.2.0
  - blas=1.0
  - bleach=4.1.0
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2021.10.26
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - cryptography=36.0.0
  - curl=7.80.0
  - cycler=0.11.0
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.4
  - fonttools=4.25.0
  - freetype=2.11.0
  - gettext=0.21.0
  - giflib=5.2.1
  - git=2.34.1
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.8.2
  - importlib_metadata=4.8.2
  - intel-openmp=2021.4.0
  - ipykernel=6.4.1
  - ipython=7.31.1
  - ipython_genutils=0.2.0
  - jedi=0.18.1
  - jinja2=3.0.2
  - jpeg=9d
  - json5=0.9.6
  - jsonschema=3.2.0
  - jupyter_client=7.1.2
  - jupyter_core=4.9.1
  - jupyter_server=1.13.5
  - jupyterlab=3.2.9
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.10.3
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - libcurl=7.80.0
  - libcxx=12.0.0
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libiconv=1.16
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.2.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - markupsafe=2.0.1
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.2
  - mistune=0.8.4
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - nbclassic=0.3.5
  - nbclient=0.5.3
  - nbconvert=6.3.0
  - nbformat=5.1.3
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - notebook=6.4.8
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openssl=1.1.1m
  - packaging=21.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.37
  - perl=5.26.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - prometheus_client=0.13.1
  - prompt-toolkit=3.0.20
  - ptyprocess=0.7.0
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=22.0.0
  - pyparsing=3.0.4
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - pytz=2021.3
  - pyzmq=22.3.0
  - readline=8.1.2
  - requests=2.27.1
  - scikit-image=0.18.3
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - send2trash=1.8.0
  - setuptools=58.0.4
  - six=1.16.0
  - sniffio=1.2.0
  - sqlite=3.37.2
  - terminado=0.13.1
  - testpath=0.5.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.37.1
  - xz=5.2.5
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9

